export const HIVE_API_TOKEN = "HIVE_ADMIN_API_TOKEN";
export const HIVE_USER_NAME = "HIVE_ADMIN_USER_NAME";
export const IS_LOGIN = "HIVE_ADMIN_IS_LOGIN"
export const HIVE_USER_PASSWORD="HIVE_ADMIN_USER_PASSWORD"
export const HIVE_REMENBER_USERNAME = "HIVE_ADMIN_REMENBER_USERNAME"

export const HIVE_ADMIN_ID = "HIVE_ADMIN_ID"
export const HIVE_ADMIN_RIGHTS = "HIVE_ADMIN_RIGHTS"
export const HIVE_ADMIN_TYPE = "HIVE_ADMIN_TYPE"

